// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtisnnvqureugwgoygsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0aXNubnZxdXJldWd3Z295Z3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTE2MjQsImV4cCI6MjA2ODQ2NzYyNH0.VOafnI4-8JtwNWc0fj5JU7yJirn6caZWcM-LIxDPdp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});